name: Deploy JSDoc To GitHub Pages

on:
  workflow_dispatch:
  release:
    types: [published]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    name: Build for GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # Setup
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'

      # Build
      - name: Build
        run: |
          npm ci --ignore-scripts --audit=false
          npm run jsdoc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: jsdoc/

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
