name: Deploy JSDoc To GitHub Pages

on:
  release:
    types: [ published ]

jobs:
  deploy:
    name: Build & Deploy to GitHub Pages
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'

      # Build
      - name: Build
        run: |
          npm ci --ignore-scripts --audit=false
          npm run jsdoc

      # Deploy
      - name: Deploy To GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./jsdoc/
